version=0.1

[default.build.parameters]
cached="true"
parallel="true"
beta_features = true

[default.deploy.parameters]
stack_name="mic-demo"
region="us-west-2"
capabilities="CAPABILITY_NAMED_IAM"
fail_on_empty_changeset = false
resolve_s3 = true
s3_prefix = "mic-demo"
profile = "NonProdAWSAdminPS-533267020610"
disable_rollback = true
image_repositories = []

